// flow-typed signature: 5608de946dbf74c46b9be225a2ae9ece
// flow-typed version: <<STUB>>/toobusy-js_v^0.5.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'toobusy-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'toobusy-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'toobusy-js/examples/express' {
  declare module.exports: any;
}

declare module 'toobusy-js/examples/http' {
  declare module.exports: any;
}

declare module 'toobusy-js/examples/load' {
  declare module.exports: any;
}

declare module 'toobusy-js/examples/standalone' {
  declare module.exports: any;
}

declare module 'toobusy-js/foo' {
  declare module.exports: any;
}

declare module 'toobusy-js/tests' {
  declare module.exports: any;
}

declare module 'toobusy-js/toobusy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'toobusy-js/examples/express.js' {
  declare module.exports: $Exports<'toobusy-js/examples/express'>;
}
declare module 'toobusy-js/examples/http.js' {
  declare module.exports: $Exports<'toobusy-js/examples/http'>;
}
declare module 'toobusy-js/examples/load.js' {
  declare module.exports: $Exports<'toobusy-js/examples/load'>;
}
declare module 'toobusy-js/examples/standalone.js' {
  declare module.exports: $Exports<'toobusy-js/examples/standalone'>;
}
declare module 'toobusy-js/foo.js' {
  declare module.exports: $Exports<'toobusy-js/foo'>;
}
declare module 'toobusy-js/index' {
  declare module.exports: $Exports<'toobusy-js'>;
}
declare module 'toobusy-js/index.js' {
  declare module.exports: $Exports<'toobusy-js'>;
}
declare module 'toobusy-js/tests.js' {
  declare module.exports: $Exports<'toobusy-js/tests'>;
}
declare module 'toobusy-js/toobusy.js' {
  declare module.exports: $Exports<'toobusy-js/toobusy'>;
}
